### ISSUE TITLE
REQUEST: View Journal Page without Editing

### ISSUE THREAD

**Issue by pesky-wobbit** [puddleimages/actor-journal-helper#12]
It's nice that the module takes you straight from the character sheet to the editor, but I wish there was separate option to go straight to the page in a normal, non-editing mode.

**Comment by puddleimages** [comment]
Are you asking for an option to go to the page instead of the editor, or are you asking for an option to have a second button that takes you to the page instead of the editor?

**Comment by pesky-wobbit** [comment]
A second button.
My disappointment was not being able to view the properly formatted journal from the character sheet.
In short, it would be nice to edit and view.

**Comment by puddleimages** [comment]
That shouldn't be to difficult. I'm going to work on that right now.

**Comment by puddleimages** [comment]
Check out the latest release and let me know if you have any other feature requests.
https://github.com/puddleimages/actor-journal-helper/releases/tag/v1.0.2
