### ISSUE TITLE
Cannot Save and Close Descriptions When Module Active

### ISSUE THREAD

**Issue by Arcane-Scholar** [puddleimages/actor-journal-helper#6]
![image](https://github.com/puddleimages/actor-journal-helper/assets/143969867/4e2b435f-6a8f-47b8-8599-6a9ddb6dd0f3)
When your module is active and I am trying to save an item, feat's description by clicking on the underlined save icon nothing happens. It edit mode stays active. Even if you close the window and return to it by double-clicking on the item from the items menu you will return to the edit mode.

My FoundryVTT is v11 Build 315 running on Ubuntu and my client is a Windows 11 running Chrome 64-bit v119.

### Recreating the Problem
With `Actor-Journal-Helper` module active:
1. Open the `Items` menu in the Right sidebar
2. Click on the `Create Item` button
![image](https://github.com/puddleimages/actor-journal-helper/assets/143969867/43016154-5e71-4fde-a110-b7f771d4cf35)
3. Enter `Test Weapon` in the `Name` text box
![image](https://github.com/puddleimages/actor-journal-helper/assets/143969867/26ff38da-db7f-4130-a3b4-ffbd4a6c347c)
4. In the dialog box choose `Weapon` from the `Type` dropdown
5. Click `Create New Item` button
6. Click the edit icon for the description
![image](https://github.com/puddleimages/actor-journal-helper/assets/143969867/a67eb3a0-520b-4e52-a312-bca59f4ba614)
7. Enter a description 
8. Attempt to click the save icon 
![image](https://github.com/puddleimages/actor-journal-helper/assets/143969867/4e2b435f-6a8f-47b8-8599-6a9ddb6dd0f3)

**Comment by puddleimages** [comment]
Thank you for bringing this up. I'll look into it. Please be patient.

**Comment by puddleimages** [comment]
I think I fixed it. The option for closing the editor upon saving was interacting poorly with windows other than the intended journal page editor windows. I'll push the changes shortly in the new release.

`
Hooks.on('getProseMirrorMenuItems', (menu, config) => {
  const saveMenuItem = config.find(item => item.action === 'save');
  const isCharacter = html.hasClass('character');
  const isNPC = html.hasClass('npc');
  if (isCharacter || isNPC) {
    saveMenuItem.cmd = () => {
      if (closeJournalPageEditorOnSave) {
        editorInstance.close();
      }
    };
  }
});
`

**Comment by puddleimages** [comment]
I broke the feature with that change... looking into possible solutions again.

**Comment by puddleimages** [comment]
I think I figured out a decent solution.

`Hooks.on('getProseMirrorMenuItems', (menu, config) => {
  console.log(menu)
  const saveMenuItem = config.find(item => item.action === 'save');
  if (menu.view.dom.className === "editor-content journal-page-content ProseMirror") {
    saveMenuItem.cmd = () => {
      if (closeJournalPageEditorOnSave) {
        editorInstance.close();
      }
    };
  }
});
`
